// dumb-script-discovery: generated by Dumb Engine. Finds every script module in src/.
use std::fmt::Write;

fn main() {
    let src = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("src");
    println!("cargo:rerun-if-changed=src");
    let mut entries: Vec<_> = std::fs::read_dir(&src).unwrap().flatten().map(|e| e.path()).collect();
    entries.sort();
    let mut mods = String::new();
    let mut calls = String::new();
    for path in entries {
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else { continue };
        let is_rs = path.extension().is_some_and(|e| e == "rs");
        let valid = !stem.is_empty()
            && stem.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
            && !stem.starts_with(|c: char| c.is_ascii_digit());
        if !is_rs || !valid || stem == "lib" || stem == "main" {
            continue;
        }
        let text = std::fs::read_to_string(&path).unwrap_or_default();
        writeln!(mods, "#[path = {:?}]\npub mod {stem};", path.display().to_string()).unwrap();
        if text.contains("pub fn register(") {
            writeln!(calls, "    {stem}::register(reg);").unwrap();
        }
    }
    let out = format!("{mods}\n/// Registers every script module (generated).\npub fn register_scripts(reg: &mut dumb_script::Registry) {{\n{calls}}}\n");
    let dest = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("scripts.rs");
    std::fs::write(dest, out).unwrap();
}
