//! Script project tooling: scaffolding a project's scripts crate, creating scripts from
//! templates, listing script files, mapping types to source files and parsing build output.
//!
//! A scripts crate discovers its modules automatically: `build.rs` scans `src/` and emits
//! `mod x;` for every file, and registers every module that defines `pub fn register`. Creating a
//! script is therefore just writing one file; nothing else needs editing.

use std::path::{Path, PathBuf};

/// Marker that identifies a build.rs written by the engine.
pub const DISCOVERY_MARKER: &str = "dumb-script-discovery";

const BUILD_RS: &str = r##"// dumb-script-discovery: generated by Dumb Engine. Finds every script module in src/.
use std::fmt::Write;

fn main() {
    let src = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("src");
    println!("cargo:rerun-if-changed=src");
    let mut entries: Vec<_> = std::fs::read_dir(&src).unwrap().flatten().map(|e| e.path()).collect();
    entries.sort();
    let mut mods = String::new();
    let mut calls = String::new();
    for path in entries {
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else { continue };
        let is_rs = path.extension().is_some_and(|e| e == "rs");
        let valid = !stem.is_empty()
            && stem.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
            && !stem.starts_with(|c: char| c.is_ascii_digit());
        if !is_rs || !valid || stem == "lib" || stem == "main" {
            continue;
        }
        // Keywords (move.rs, type.rs...) become raw identifiers; a few can't be used at all.
        const KEYWORDS: &[&str] = &[
            "as", "async", "await", "break", "const", "continue", "dyn", "else", "enum", "extern", "false", "fn", "for", "if", "impl", "in",
            "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return", "static", "struct", "trait", "true", "type", "unsafe", "use",
            "where", "while", "abstract", "become", "box", "do", "final", "gen", "macro", "override", "priv", "try", "typeof", "unsized",
            "virtual", "yield",
        ];
        if matches!(stem, "self" | "super" | "crate" | "Self") {
            println!("cargo:warning=script file `{stem}.rs` can't be a module name; rename it");
            continue;
        }
        let ident = if KEYWORDS.contains(&stem) { format!("r#{stem}") } else { stem.to_string() };
        let text = std::fs::read_to_string(&path).unwrap_or_default();
        writeln!(mods, "#[path = {:?}]\npub mod {ident};", path.display().to_string()).unwrap();
        if text.contains("pub fn register(") {
            writeln!(calls, "    {ident}::register(reg);").unwrap();
        }
    }
    let out = format!("{mods}\n/// Registers every script module (generated).\npub fn register_scripts(reg: &mut dumb_script::Registry) {{\n{calls}}}\n");
    let dest = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("scripts.rs");
    std::fs::write(dest, out).unwrap();
}
"##;

const LIB_RS: &str = r#"//! Game scripts. Every `.rs` file in this folder is a script module and is found
//! automatically (see build.rs); modules with `pub fn register(reg: &mut Registry)`
//! are registered with the engine. Create scripts from the editor (Scripts ▸ New Script).

include!(concat!(env!("OUT_DIR"), "/scripts.rs"));

dumb_script::export_plugin!(register_scripts);
"#;

/// Write a scripts crate at `dir`. `engine_root` is the engine repository (for path dependencies).
/// If `lockfile` is given it is copied so the crate builds against the exact same dependency
/// versions as the engine (Rust has no stable ABI).
pub fn create_scripts_crate(dir: &Path, package: &str, engine_root: &Path, lockfile: Option<&Path>) -> std::io::Result<()> {
    std::fs::create_dir_all(dir.join("src"))?;
    let rel = pathdiff(&normalize(engine_root), &normalize(dir));
    let crates = rel.join("crates");
    let dep = |name: &str| format!("{name} = {{ path = {:?} }}\n", crates.join(name).to_string_lossy().replace('\\', "/"));
    let manifest = format!(
        "[package]\nname = \"{package}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n\
         [lib]\ncrate-type = [\"cdylib\"]\n\n\
         [dependencies]\n{}{}{}{}log = \"0.4\"\n\n\
         # Same optimization settings as the engine so the editor and scripts agree.\n\
         [profile.dev]\nopt-level = 1\n\n[profile.dev.package.\"*\"]\nopt-level = 3\n\n\
         # A standalone workspace: the scripts build on their own, in Scripts/target.\n[workspace]\n",
        dep("dumb_core"),
        dep("dumb_reflect"),
        dep("dumb_ecs"),
        dep("dumb_script"),
    );
    std::fs::write(dir.join("Cargo.toml"), manifest)?;
    std::fs::write(dir.join("build.rs"), BUILD_RS)?;
    if !dir.join("src/lib.rs").exists() {
        std::fs::write(dir.join("src/lib.rs"), LIB_RS)?;
    }
    std::fs::write(dir.join(".gitignore"), "/target\n")?;
    if let Some(lock) = lockfile.filter(|l| l.exists()) {
        std::fs::copy(lock, dir.join("Cargo.lock"))?;
    }
    Ok(())
}

/// Absolute path without Windows' `\\?\` verbatim prefix (cargo can't use those).
fn normalize(p: &Path) -> PathBuf {
    let abs = if p.is_absolute() { p.to_path_buf() } else { std::env::current_dir().map(|d| d.join(p)).unwrap_or_else(|_| p.to_path_buf()) };
    let s = abs.to_string_lossy().into_owned();
    let s = s.strip_prefix(r"\\?\").map(str::to_string).unwrap_or(s);
    // Resolve `..` lexically so relative-path computation sees clean components.
    let mut out = PathBuf::new();
    for c in Path::new(&s).components() {
        match c {
            std::path::Component::ParentDir => {
                out.pop();
            }
            std::path::Component::CurDir => {}
            c => out.push(c.as_os_str()),
        }
    }
    out
}

/// Relative path from `base` to `target` when they share a root, else `target` itself.
fn pathdiff(target: &Path, base: &Path) -> PathBuf {
    let t: Vec<_> = target.components().collect();
    let b: Vec<_> = base.components().collect();
    let common = t.iter().zip(&b).take_while(|(a, b)| a == b).count();
    if common == 0 {
        return target.to_path_buf();
    }
    let mut out = PathBuf::new();
    for _ in common..b.len() {
        out.push("..");
    }
    for c in &t[common..] {
        out.push(c.as_os_str());
    }
    out
}

/// Turn a package name into a valid crate name (`My Game!` -> `my_game`).
pub fn crate_name(name: &str) -> String {
    let mut s = to_snake(name);
    if s.is_empty() || s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert_str(0, "game_");
    }
    s
}

/// `EnemyAI`, `enemy ai`, `enemy-ai` -> `enemy_ai`.
pub fn to_snake(name: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = name.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_ascii_alphanumeric() {
            let prev = i.checked_sub(1).map(|j| chars[j]);
            let next = chars.get(i + 1).copied();
            let boundary = c.is_ascii_uppercase()
                && prev.is_some_and(|p| p.is_ascii_lowercase() || p.is_ascii_digit() || (p.is_ascii_uppercase() && next.is_some_and(|n| n.is_ascii_lowercase())));
            if boundary && !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else if !out.is_empty() && !out.ends_with('_') {
            out.push('_');
        }
    }
    out.trim_end_matches('_').to_string()
}

/// `enemy ai`, `enemy_ai`, `EnemyAI` -> `EnemyAi` / `EnemyAI` (existing capitals are kept).
pub fn to_pascal(name: &str) -> String {
    name.split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut c = w.chars();
            let first = c.next().unwrap().to_ascii_uppercase();
            std::iter::once(first).chain(c).collect::<String>()
        })
        .collect()
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ScriptTemplate {
    /// Component with fields + a system that updates it every frame.
    Behaviour,
    /// Data-only component.
    Component,
    /// A system without its own component.
    System,
    /// A helper module (nothing registered).
    Empty,
}

impl ScriptTemplate {
    pub const ALL: [ScriptTemplate; 4] = [ScriptTemplate::Behaviour, ScriptTemplate::Component, ScriptTemplate::System, ScriptTemplate::Empty];

    pub fn label(&self) -> &'static str {
        match self {
            ScriptTemplate::Behaviour => "Behaviour (component + system)",
            ScriptTemplate::Component => "Component (data only)",
            ScriptTemplate::System => "System",
            ScriptTemplate::Empty => "Empty module",
        }
    }

    pub fn source(&self, type_name: &str, module: &str) -> String {
        match self {
            ScriptTemplate::Behaviour => format!(
                r#"use dumb_script::prelude::*;

/// Add this to an entity from the inspector (Add Component ▸ {type_name}).
#[derive(Component, Editor, Clone, Debug)]
pub struct {type_name} {{
    #[editor(range = 0.0..=20.0, tooltip = "Units per second")]
    pub speed: f32,
    pub enabled: bool,
}}

impl Default for {type_name} {{
    fn default() -> Self {{
        {type_name} {{ speed: 1.0, enabled: true }}
    }}
}}

/// Runs every frame while the game is playing.
fn update(ctx: &mut ScriptContext) {{
    let dt = ctx.time.delta;
    for (transform, script) in ctx.world.query::<(&mut Transform, &{type_name})>() {{
        if !script.enabled {{
            continue;
        }}
        transform.translation.y += (ctx.time.elapsed as f32).sin() * script.speed * dt;
    }}
}}

pub fn register(reg: &mut Registry) {{
    reg.component::<{type_name}>();
    reg.system("{module}::update", update);
}}
"#
            ),
            ScriptTemplate::Component => format!(
                r#"use dumb_script::prelude::*;

#[derive(Component, Editor, Clone, Debug, Default)]
pub struct {type_name} {{
    pub value: f32,
    #[editor(asset = "model")]
    pub model: AssetId,
}}

pub fn register(reg: &mut Registry) {{
    reg.component::<{type_name}>();
}}
"#
            ),
            ScriptTemplate::System => format!(
                r#"use dumb_script::prelude::*;

/// Runs every frame while the game is playing.
fn {module}(ctx: &mut ScriptContext) {{
    if ctx.input.key_pressed(Key::Space) {{
        log::info!("{{}} entities at t={{:.2}}s", ctx.world.entity_count(), ctx.time.elapsed);
    }}
}}

pub fn register(reg: &mut Registry) {{
    reg.system("{module}", {module});
}}
"#
            ),
            ScriptTemplate::Empty => "use dumb_script::prelude::*;\n\n// Helper code shared by other scripts (`crate::module::item`).\n".to_string(),
        }
    }
}

/// Create `src/<snake>.rs` from a template. Returns the file path.
pub fn create_script(crate_dir: &Path, name: &str, template: ScriptTemplate) -> Result<PathBuf, String> {
    let type_name = to_pascal(name);
    let module = to_snake(name);
    if type_name.is_empty() || module.is_empty() || module.starts_with(|c: char| c.is_ascii_digit()) {
        return Err("Script names must start with a letter".into());
    }
    if ["lib", "main", "mod", "self", "super", "crate", "type", "fn", "struct", "impl", "use", "match", "loop"].contains(&module.as_str()) {
        return Err(format!("`{module}` is a reserved name"));
    }
    let path = crate_dir.join("src").join(format!("{module}.rs"));
    if path.exists() {
        return Err(format!("{} already exists", path.display()));
    }
    std::fs::create_dir_all(crate_dir.join("src")).map_err(|e| e.to_string())?;
    std::fs::write(&path, template.source(&type_name, &module)).map_err(|e| e.to_string())?;
    Ok(path)
}

#[derive(Clone, Debug)]
pub struct ScriptFile {
    pub path: PathBuf,
    pub module: String,
    /// Has `pub fn register`, so it is registered with the engine.
    pub registered: bool,
    pub lines: usize,
}

/// Script files in `src/` (excluding lib.rs), sorted by name.
pub fn list_scripts(crate_dir: &Path) -> Vec<ScriptFile> {
    let Ok(rd) = std::fs::read_dir(crate_dir.join("src")) else { return Vec::new() };
    let mut out: Vec<ScriptFile> = rd
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "rs"))
        .filter(|p| p.file_stem().is_some_and(|s| s != "lib" && s != "main"))
        .map(|p| {
            let text = std::fs::read_to_string(&p).unwrap_or_default();
            ScriptFile {
                module: p.file_stem().unwrap().to_string_lossy().into_owned(),
                registered: text.contains("pub fn register("),
                lines: text.lines().count(),
                path: p,
            }
        })
        .collect();
    out.sort_by(|a, b| a.module.cmp(&b.module));
    out
}

/// Whether a crate uses automatic module discovery.
pub fn uses_discovery(crate_dir: &Path) -> bool {
    std::fs::read_to_string(crate_dir.join("build.rs")).is_ok_and(|s| s.contains(DISCOVERY_MARKER))
}

/// Source file that defines a reflected type, from its type path
/// (`my_scripts::enemy::Enemy` -> `src/enemy.rs`, `my_scripts::Enemy` -> `src/lib.rs`).
pub fn source_for_type(crate_dir: &Path, type_name: &str) -> Option<PathBuf> {
    let parts: Vec<&str> = type_name.split("::").collect();
    if parts.len() < 2 {
        return None;
    }
    let modules = &parts[1..parts.len() - 1];
    let src = crate_dir.join("src");
    if modules.is_empty() {
        return Some(src.join("lib.rs")).filter(|p| p.exists());
    }
    let mut p = src.clone();
    for m in &modules[..modules.len() - 1] {
        p.push(m);
    }
    let last = modules[modules.len() - 1];
    [p.join(format!("{last}.rs")), p.join(last).join("mod.rs")].into_iter().find(|f| f.exists())
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MessageLevel {
    Error,
    Warning,
}

/// A compiler diagnostic with a source location.
#[derive(Clone, Debug)]
pub struct BuildMessage {
    pub level: MessageLevel,
    pub file: PathBuf,
    pub line: u32,
    pub column: u32,
    pub text: String,
}

/// Parse `cargo --message-format=short` lines (`src\x.rs:12:5: error[E0308]: ...`).
pub fn parse_build_messages(lines: &[String], crate_dir: &Path) -> Vec<BuildMessage> {
    let mut out = Vec::new();
    for l in lines {
        let Some(rs) = l.find(".rs:") else { continue };
        let file = &l[..rs + 3];
        let mut rest = l[rs + 4..].splitn(3, ':');
        let (Some(line), Some(col), Some(text)) = (rest.next(), rest.next(), rest.next()) else { continue };
        let (Ok(line), Ok(column)) = (line.trim().parse::<u32>(), col.trim().parse::<u32>()) else { continue };
        let text = text.trim();
        let level = if text.starts_with("error") {
            MessageLevel::Error
        } else if text.starts_with("warning") {
            MessageLevel::Warning
        } else {
            continue;
        };
        let p = PathBuf::from(file.trim());
        let file = if p.is_absolute() { p } else { crate_dir.join(p) };
        out.push(BuildMessage { level, file, line, column, text: text.to_string() });
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names() {
        assert_eq!(to_snake("EnemyAI"), "enemy_ai");
        assert_eq!(to_snake("enemy ai"), "enemy_ai");
        assert_eq!(to_snake("PlayerController2"), "player_controller2");
        assert_eq!(to_snake("HTTPServer"), "http_server");
        assert_eq!(to_pascal("enemy ai"), "EnemyAi");
        assert_eq!(to_pascal("EnemyAI"), "EnemyAI");
        assert_eq!(crate_name("My Game!"), "my_game");
        assert_eq!(crate_name("3D Thing"), "game_3_d_thing");
    }

    #[test]
    fn parses_short_messages() {
        let lines = vec![
            r"src\enemy.rs:12:5: error[E0425]: cannot find value `x` in this scope".to_string(),
            "src/player.rs:3:1: warning: unused import: `Vec3`".to_string(),
            "   Compiling foo v0.1.0".to_string(),
        ];
        let m = parse_build_messages(&lines, Path::new("C:/p/Scripts"));
        assert_eq!(m.len(), 2);
        assert_eq!(m[0].line, 12);
        assert_eq!(m[0].column, 5);
        assert_eq!(m[0].level, MessageLevel::Error);
        assert!(m[0].file.ends_with("src\\enemy.rs") || m[0].file.ends_with("src/enemy.rs"));
        assert_eq!(m[1].level, MessageLevel::Warning);
    }

    #[test]
    fn type_to_source() {
        let dir = std::env::temp_dir().join(format!("dumb_src_test_{}", std::process::id()));
        std::fs::create_dir_all(dir.join("src")).unwrap();
        std::fs::write(dir.join("src/enemy.rs"), "").unwrap();
        std::fs::write(dir.join("src/lib.rs"), "").unwrap();
        assert_eq!(source_for_type(&dir, "g::enemy::Enemy"), Some(dir.join("src").join("enemy.rs")));
        assert_eq!(source_for_type(&dir, "g::Enemy"), Some(dir.join("src").join("lib.rs")));
        assert_eq!(source_for_type(&dir, "g::nope::X"), None);
        std::fs::remove_dir_all(dir).ok();
    }

    #[test]
    fn relative_engine_path() {
        assert_eq!(pathdiff(Path::new("D:/dev/engine"), Path::new("D:/dev/engine/project/Scripts")), PathBuf::from("../.."));
        assert_eq!(pathdiff(Path::new("D:/dev/engine"), Path::new("D:/games/x/Scripts")), PathBuf::from("../../../dev/engine"));
    }
}

/// Update the generated build.rs of an existing scripts crate to this engine's version
/// (it is engine-owned: fixes to module discovery reach old projects too).
pub fn refresh_generated(dir: &Path) -> std::io::Result<bool> {
    let p = dir.join("build.rs");
    match std::fs::read_to_string(&p) {
        Ok(s) if s.contains(DISCOVERY_MARKER) && s != BUILD_RS => {
            std::fs::write(&p, BUILD_RS)?;
            Ok(true)
        }
        _ => Ok(false),
    }
}
